version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=acme_ltd
    networks:
      - dc1ring

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=my_cluster
    networks:
      - dc1ring

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=my_cluster
    networks:
      - dc1ring

  fastapi:
    image: "${COMPOSE_PROJECT_NAME}/api:1.0"
    container_name: fastapi
    volumes: 
      - ./app:/usr/app
    ports:
      - 8000:80
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
    networks:
      - dc1ring

networks:
  dc1ring:
